name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Pack
        run: dotnet pack --configuration Release --output releases /p:Version=${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Publish
        run: dotnet nuget push ./releases/*.nupkg --api-key ${{ secrets.PAT }} --source https://api.nuget.org/v3/index.json
      - name: Tag
        uses: mathieudutour/github-tag-action@v6.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{ steps.gitversion.outputs.nuGetVersion }}
