name: Release

on:
  milestone:
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x
      - name: Pack
        run: dotnet pack --configuration Release --output releases /p:Version=${{ github.event.milestone.title }}
      - name: Publish
        run: dotnet nuget push ./releases/*.nupkg --api-key ${{ secrets.NUGET }} --source "https://nuget.pkg.github.com/ionalexandru99/index.json" --skip-duplicate
      - name: Tag
        uses: mathieudutour/github-tag-action@v6.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{ github.event.milestone.title }}
